//
// Created by snickers on 11/22/19.
//

#ifndef PROJECT_NAME_GPIO_H
#define PROJECT_NAME_GPIO_H


#define ERROR_GPIO_GPIO_Port GPIOC
#define CH0_INDICATOR_PORT GPIOB
#define CH1_INDICATOR_PORT GPIOB
#define CH2_INDICATOR_PORT GPIOB
#define CH3_INDICATOR_PORT GPIOB
#define CH4_INDICATOR_PORT GPIOB
#define CH5_INDICATOR_PORT GPIOA
#define CH6_INDICATOR_PORT GPIOA
#define CH7_INDICATOR_PORT GPIOA
#define TARGET_SELECT_0_MUX_DRIVER_PORT GPIOA
#define TARGET_SELECT_1_MUX_DRIVER_PORT GPIOA
#define TARGET_SELECT_2_MUX_DRIVER_PORT GPIOA
#define TARGET_SELECT_MAN_SW_PORT GPIOB
#define TARGET_RESET_MAN_SW_PORT GPIOB
#define J_NRES_DISABLE_PORT GPIOA
#define HERD_RES_ALL_PORT GPIOA
#define USB_POWER_INDICATOR_PORT GPIOA


#define ERROR_GPIO_Pin GPIO_PIN_13
#define CH0_INDICATOR_PIN GPIO_PIN_12
#define CH1_INDICATOR_PIN GPIO_PIN_11
#define CH2_INDICATOR_PIN GPIO_PIN_10
#define CH3_INDICATOR_PIN GPIO_PIN_1
#define CH4_INDICATOR_PIN GPIO_PIN_0
#define CH5_INDICATOR_PIN GPIO_PIN_7
#define CH6_INDICATOR_PIN GPIO_PIN_4
#define CH7_INDICATOR_PIN GPIO_PIN_3
#define TARGET_SELECT_0_MUX_DRIVER_PIN GPIO_PIN_0
#define TARGET_SELECT_1_MUX_DRIVER_PIN GPIO_PIN_1
#define TARGET_SELECT_2_MUX_DRIVER_PIN GPIO_PIN_2
#define TARGET_SELECT_MAN_SW_PIN GPIO_PIN_5
#define TARGET_RESET_MAN_SW_PIN GPIO_PIN_6
#define J_NRES_DISABLE_PIN GPIO_PIN_6
#define HERD_RES_ALL_PIN GPIO_PIN_5
#define USB_POWER_INDICATOR_PIN GPIO_PIN_8



#endif //PROJECT_NAME_GPIO_H
